### ISSUE TITLE
Images Not Showing

### ISSUE THREAD

**Issue by WaterKH** [SCCapstone/Ingredi-Scan#17]
On the search page, sometimes images will not load and an error will be caught in the Console.

**Comment by z2oh** [comment]
I was unable to reproduce this error. I tried searching about 15 different terms and all the images showed up appropriately (sometimes with a small delay). Do you have steps to reproduce this bug?

**Comment by WaterKH** [comment]
Could just be the emulator I was using. Maybe have @evanskendall6 test on his phone to see if there appears to be anything wrong there.

**Comment by z2oh** [comment]
Closing until further notice.
