### ISSUE TITLE
Add Functionality

### ISSUE THREAD

**Issue by WaterKH** [SCCapstone/Ingredi-Scan#21]
Add functionality to the 
- [x] delete from cart
- [x] add to cart

**Comment by WaterKH** [comment]
@logandowd We'll probably need to tag team this since you'll be designing the Cart, but we can also do that together if you need!

**Comment by z2oh** [comment]
Can we re-evaluate if we need searching and editing? Deleting and adding are obviously critical, but are the other features as well?
