### ISSUE TITLE
Scroll Freeze

### ISSUE THREAD

**Issue by WaterKH** [SCCapstone/Ingredi-Scan#24]
The Settings page freezes when you scroll too fast.

**Comment by z2oh** [comment]
For me the settings page freezes as soon as it is opened. I'm getting a System.Net.Http.HttpRequestException: 401 (Unauthorized) error as soon as I open the settings page that causes a crash. Could these be related?

**Comment by z2oh** [comment]
Settings now works for me. I'm not sure what the problem was before... some kind of authorization error I think.

**Comment by WaterKH** [comment]
Can we close this for now?
