### ISSUE TITLE
Saving Settings

### ISSUE THREAD

**Issue by WaterKH** [SCCapstone/Ingredi-Scan#27]
+ Save icon may be confusing. 
+ Make saving asynchronous, make it update when trigger is hit.

**Comment by evanskendall6** [comment]
Didn't realize this was an issue, mostly solved this problem with my last commit. Still need a way to clear settings.

**Comment by WaterKH** [comment]
Change Icon.

**Comment by WaterKH** [comment]
Functionality implemented and settings now completely reset.
