### ISSUE TITLE
Full Recipe Title

### ISSUE THREAD

**Issue by evanskendall6** [SCCapstone/Ingredi-Scan#33]
Title of some recipes are cut off with no way to view the whole title

**Comment by z2oh** [comment]
Is this happening in the cart page or on the search page?

**Comment by z2oh** [comment]
![capture](https://cloud.githubusercontent.com/assets/385684/24822894/f47fd0d6-1bc6-11e7-903e-edc45adedd6b.PNG)

The full recipe name is now shown in the recipe detail view.
