### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by WaterKH** [SCCapstone/Ingredi-Scan#36]
Everyone will take a page, just comment which page you will be taking.

**Comment by WaterKH** [comment]
I'll take the Favorites since that shouldn't have a lot of code to it.

**Comment by philipaconrad** [comment]
Have you all made any progress on your unit tests?

**Comment by z2oh** [comment]
We have created one unit test and one behavioral test. Because all the business logic in our app is handled by back end services (Spoonacular API, Zebra X-Ing, Auth0, and Firebase), these isn't really much for us to unit test.
