### ISSUE TITLE
Shopping cart can be sorted by food item

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#42]
- [ ] Amounts get added up (1 garlic + 3 garlic becomes 4 garlic)

**Comment by josemvidal** [comment]
Not working, at all.

Might be due to me using my old google account due to #51

**Comment by z2oh** [comment]
This was **re**-added via 9733cfca9103e3ffb47b3d4fc7ca518af4a67c4e. Some commit since d70791f must have clobbered my changes. Re-closing.
