### ISSUE TITLE
Shopping cart uses checkboxes, not toggle boxes.

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#43]

**Comment by evanskendall6** [comment]
Implemented but not great yet.

**Comment by evanskendall6** [comment]
Previous commits have improved this. Closing

**Comment by josemvidal** [comment]
Right now, the shopping cart has neither checkboxes nor toggle boxes. 

This might be related to me having to use my Google account and #52 

In any case, no checkboxes. I am re-opening this.

@philipaconrad please verify.

**Comment by josemvidal** [comment]
This might be due to an invisible checkbox, and having to make the tap event activated by the whole row.

**Comment by z2oh** [comment]
I can see the checkboxes on my emulator. This must have been fixed by something in the past 13 days, so I'm closing for now but will keep an eye on this in case it resurfaces.
