### ISSUE TITLE
Make Settings Page clearer

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#47]
<img width="399" alt="android_emulator_-_pixel_api_25_5554" src="https://cloud.githubusercontent.com/assets/228704/23657967/a95fd0e0-030e-11e7-8403-dafd5bf5890d.png">

**Comment by z2oh** [comment]
Do we want checkboxes here instead? I guess we need to look into how the api actually allows us to modify these selections. i.e. do we exclude cuisines or include cuisines, and if we include 0 does that default to include all?

**Comment by evanskendall6** [comment]
My previous commit should take care of this. Going to close for now.

**Comment by josemvidal** [comment]
All you did was add the text "Mark Items to Narrow Search".

It is an improvement, but by not much.
