### ISSUE TITLE
Beta release APK crashes in emulator on login with non-Google account

### ISSUE THREAD

**Issue by philipaconrad** [SCCapstone/Ingredi-Scan#48]
## Description

Once I log in, the app crashes in the emulator. This occurred during the sign up process as well.

This crash occurs consistently.

## How to repro

Testing was done with a Nexus 5 AVD image, API version 23.

 1. Create a new user account under the Sign Up page.
 1. The app will crash.
 1. Go to your email and verify the account.
 1. Re-open app.
 1. Attempt to log in with your account.

## Additional details

Attached is a GIF of me trying to log in after creating an account.
![peek 2017-03-10 20-35](https://cloud.githubusercontent.com/assets/1906841/23819212/3ca42116-05d1-11e7-8178-ebaf7ea64bdd.gif)

**Comment by WaterKH** [comment]
This is because we only support google accounts. We will have this fixed in the RC1.

**Comment by philipaconrad** [comment]
Ah, I'll try with one of my Google accounts for now. Definitely fix this up for RC1 though.

**Comment by philipaconrad** [comment]
Yeah, works well with the Google account.
