### ISSUE TITLE
RC1 release only runs on arm: PRIORITY

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#50]
This release will not run on an x86 emulator. It is compiled for arm.

> Failed to install /Users/jmvidal/Desktop/com.ingrediscan.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

It runs on OK on my Pixel phone, which is where I will be testing. So I don't need a fix.

But, other people might need an .apk that can run on an x86 emulator. If they do, a solution will have to be found. 

I am adding this issue here so others will know why it is not running for them.

**Comment by josemvidal** [comment]
@philipaconrad can you run the apk?

**Comment by philipaconrad** [comment]
No, I'm afraid not. I only have access to an x86 emulator instance.

**Comment by josemvidal** [comment]
@SCCapstone/ingredi-scan please build a release on x86 so the TA (and possible the testers) can test your app.

**Comment by z2oh** [comment]
https://github.com/SCCapstone/Ingredi-Scan/releases/tag/rc1_x86

Try this release. I rebuilt with support for all supported architectures, so this should be able to run on whatever you are using.

**Comment by josemvidal** [comment]
@philipaconrad can you verify that you can run it? If so, close this.

**Comment by philipaconrad** [comment]
Can confirm x86 build works. Thank you!
