### ISSUE TITLE
After user logs out, app crashes every time you start it.

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#51]
(No gif because #50) but I tried to login with the wrong credentials and it crashes.

Then it crashes again every time I restart it. So, I have to uninstall it. Install it again.

**Comment by josemvidal** [comment]
Actually, this also happens when I try to login with a newly created account. Changing title.

**Comment by josemvidal** [comment]
@philipaconrad can you verify?

**Comment by josemvidal** [comment]
Changed title to better reflect bug. I think the same thing happens if you log in incorrectly.

**Comment by philipaconrad** [comment]
Can confirm.

After logout, everything is broken.
