### ISSUE TITLE
Delete all Items from Shopping cart does nothing

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Ingredi-Scan#52]
All items stay in my shopping card. I have about 40.

I am using my Google account because of #51 .

**Comment by josemvidal** [comment]
![marlinn2g47ejmvidal04082017091332](https://cloud.githubusercontent.com/assets/228704/24829208/d0a4f4fa-1c3b-11e7-8522-47a08a9af4e3.gif)

**Comment by z2oh** [comment]
This is now being tracked in issue #21. Closing.

**Comment by josemvidal** [comment]
Still not working.
![untitled](https://cloud.githubusercontent.com/assets/228704/25558965/8ee952b6-2cff-11e7-856c-4be1f1cc2bc6.gif)

**Comment by WaterKH** [comment]
You have to mark the items you want to delete.

**Comment by josemvidal** [comment]
Ok. By "Delete All Items" I meant a button that deletes all the items. 

To delete one item in mobile we typically swipe left on the item.

Re-labeling this as enhancement.

**Comment by WaterKH** [comment]
Ahh Okay, but you can mark multiple items and then select delete to batch delete the marked items.
