### ISSUE TITLE
App crashes after logging in

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#54]
When I log into the app using the account I created, it immediately crashes on both an emulator with SDK level 23 and an actual Android phone with SDK level 24.

**Comment by WaterKH** [comment]
This is already an issue - You'll need to login with a google account.

**Comment by cnovotny915** [comment]
Okay I used a Google account and it works now. Closing.

**Comment by philipaconrad** [comment]
Duplicate of bug reported in: https://github.com/SCCapstone/Ingredi-Scan/issues/48
