### ISSUE TITLE
App crashes when attempting to add to shopping cart

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#56]
I clicked the plus button on the Shopping Cart page, the keyboard popped up but there's no text field, and then the app crashed and continues to crash even after restarting.

**Comment by cnovotny915** [comment]
The text field is appearing now but still the same results. See new issue.

**Comment by philipaconrad** [comment]
Instead of  creating a new issue, it might have been more productive to update and continue this one.

At any rate, the conversation continues in: https://github.com/SCCapstone/Ingredi-Scan/issues/57

**Comment by philipaconrad** [comment]
Marking this as a duplicate so others will be less likely to waste time on this dead issue.
