### ISSUE TITLE
App immediately crashes after logging in

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#58]
Most of the time (7 out of ten times now) when I attempt to run the app after uninstalling and reinstalling, I log in with my Google account, the Scan screen pops up for a few seconds, and then the app immediately crashes.

**Comment by z2oh** [comment]
Could you provide some info on your device/emulator? I have been unable to reproduce this thus far.

**Comment by cnovotny915** [comment]
The device I used was a Samsung Galaxy S6 with API level 24. The emulator I used was a Nexus 6 with API level 23.

**Comment by z2oh** [comment]
Using an emulator with Nexus 6 API level 23 I am unable to reproduce this crashing. Perhaps you were attempting to login with a non-google account? Closing unless more information surfaces or the crash can be (somewhat reliably) reproduced.

**Comment by philipaconrad** [comment]
Probable duplicate of: https://github.com/SCCapstone/Ingredi-Scan/issues/51
