### ISSUE TITLE
Entering Google Account information in email and password fields fails

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#59]
Signing in with my Google Account works when I click "Log in with Google", but my credentials are not recognized when I try entering my information in the email and password fields on the log in screen. If you can only have a Google account and can only log in using the Google log in link, then the additional and password fields seem like they are unnecessary and should be removed entirely
![screenshot_1492205489](https://cloud.githubusercontent.com/assets/15602792/25056648/3a4c6c5c-2138-11e7-8289-82e2d30626b8.png)

**Comment by philipaconrad** [comment]
Marking this as `invalid`, since the app probably only can work with Google accounts when going through the "Log in with Google" system (OAuth tokens and whatnot).

That said, it would be a nice enhancement to warn users in an FAQ or something about this behavior.

**Comment by z2oh** [comment]
We have since completely disabled logging in without a google account.
