### ISSUE TITLE
Orange background does not contrast well with blue text

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#61]
I assume the shade of orange is the complement of the shade of blue, but it makes the text difficult to read.  Bold text would likely be more legible and aesthetically pleasing with the current colors.
![screenshot_1492205780](https://cloud.githubusercontent.com/assets/15602792/25056852/7ad53280-2139-11e7-8e3c-c7c19995a1c9.png)

**Comment by z2oh** [comment]
While I agree that the color makes the text difficult to read, since the color is only visible after the user has pressed the option (presumably after having already read it) this is a wontfix.
