### ISSUE TITLE
"Search without Ingredients" text field should be larger

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#62]
The text is cut off after only a few letters for a field that could have very long text. The "Number of Items to List" and the "Search Without Ingredient(s)" TextViews are unnecessary and should be removed (greatly improves readability and editability for search without ingredients).

Also, the "Search By Ingredients or Recipe Na..." title should not be cut off. Either shorten the text or expand its size so everything fits on the screen.

![screenshot_1492206235](https://cloud.githubusercontent.com/assets/15602792/25056932/086242fa-213a-11e7-9ef7-a352111fbb7d.png)

**Comment by z2oh** [comment]
![capture](https://cloud.githubusercontent.com/assets/385684/25257680/9ffc4422-2607-11e7-9eb7-651f8d0fa52b.PNG)

Thanks for bringing this to our attention. Pushing a fix momentarily.
