### ISSUE TITLE
Search Without Ingredients does not work

### ISSUE THREAD

**Issue by cnovotny915** [SCCapstone/Ingredi-Scan#63]
I added "peanuts" to the "Search Without Ingredients" text field in settings and saved them, but the first option that comes up when I search "salad" is literally called "Cabbage Salad with Peanuts".

![screenshot_1492206782](https://cloud.githubusercontent.com/assets/15602792/25057128/34a9aa0a-213b-11e7-9cf1-bc9285bed75a.png)

![screenshot_1492206662](https://cloud.githubusercontent.com/assets/15602792/25057110/1714eb30-213b-11e7-943d-1526ef4b353d.png)

**Comment by z2oh** [comment]
I think this may have been a caching issue. I have just verified that this feature works.
