### ISSUE TITLE
Compressing java folder(minor fix)

### ISSUE THREAD

**Issue by cooper757** [SCCapstone/Ingredi-Scan#65]
Compress you java folder so that it is only showing com ->your material. I'm not sure if you client is strict when it comes to how your directories should look. However, doing this process will make it easier for the user to find what they are looking for.

![ingred pics](https://cloud.githubusercontent.com/assets/10860842/25115184/69c4e5ee-23d2-11e7-9cde-0c78861b7a1b.png)

**Comment by philipaconrad** [comment]
Duplicate of: https://github.com/SCCapstone/Ingredi-Scan/issues/66
