### ISSUE TITLE
Compressing Java folder(minor fix)

### ISSUE THREAD

**Issue by cooper757** [SCCapstone/Ingredi-Scan#66]
Compress you java folder so that it is only showing com ->your material. I'm not sure if you client is strict when it comes to how your directories should look. However, doing this process will make it easier for the user to find what they are looking for.
![ingred pics](https://cloud.githubusercontent.com/assets/10860842/25115534/027b0c3a-23d5-11e7-9a5a-b33f62922b22.png)

**Comment by z2oh** [comment]
I'm afraid I'm not sure where you are seeing this. Could you possibly give some more information?

**Comment by z2oh** [comment]
Not sure what this means and I cannot find what's going on with this so I'm going to go ahead and close it. Feel free to reopen if you have any more information; if there is a problem I want it to be fixed but I'm just not sure what the issue here is.
